[PHP]

[XDEBUG] 
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_port=9003
xdebug.client_host=${LANDO_HOST_IP}
xdebug.log=/tmp/xdebug.log
xdebug.log_level = 0

; Remote settings
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_host = ${LANDO_HOST_IP}
xdebug.remote_log=/tmp/xdebug.log

; Increase the maximum array/object depth
xdebug.max_depth = 10

; Increase the maximum number of array elements and object properties
xdebug.max_children = 512

; Increase the maximum string length
xdebug.max_data = 16384

; Increase memory limit so we can profile large requests
xdebug.memory_limit = 512M

memory_limit = 4G